spring.application.name=student-attendance


spring.datasource.url=jdbc:postgresql://localhost:5432/student-attendance
spring.datasource.username=postgres
spring.datasource.password=abbasssamson1234
spring.jpa.hibernate.ddl-auto=update